name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install ghp-import  # Ensure ghp-import is installed

    - name: Update skills tags
      run: |
        source venv/bin/activate
        python update_skills_tags.py
        echo "✅ Skills tags updated"

    - name: Build site
      run: |
        source venv/bin/activate
        make html  # This generates the static files into the 'output' directory
        echo "✅ Site built successfully"

    - name: Deploy to GitHub Pages
      run: |
        source venv/bin/activate
        ghp-import -n -p -f output -b gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

