name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build site
      run: |
        source venv/bin/activate
        make html  # This generates the static files into the 'output' directory

    - name: Deploy to GitHub Pages
      run: |
        source venv/bin/activate
        git fetch origin main
        git checkout main
        git pull origin gh-pages  # Update gh-pages with the latest from main
        ghp-import output -b gh-pages -p
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
